apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: svc-3
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: svc-3
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
