apiVersion: v1
kind: Service
metadata:
    namespace: logpost
    name: svc-3
    labels:
        app: svc-3
spec:
    selector:
        app: svc-3
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8082
    type: LoadBalancer
