apiVersion: v1
kind: Service
metadata:
    namespace: logpost
    name: svc-5
    labels:
        app: svc-5
spec:
    selector:
        app: svc-5
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
    type: LoadBalancer
