apiVersion: v1
kind: Service
metadata:
    namespace: logpost
    name: svc-4
    labels:
        app: svc-4
spec:
    selector:
        app: svc-4
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8083
    type: LoadBalancer
