apiVersion: v1
kind: Service
metadata:
    namespace: logpost
    name: svc-1
    labels:
        app: svc-1
spec:
    selector:
        app: svc-1
    ports:
        - port: 80
          protocol: TCP
          targetPort: 5000
    type: LoadBalancer
